export const GET_PLAYERS = "GET_PLAYERS";
export const ADD_PLAYER = "ADD_PLAYER";
export const UPDATE_PLAYER = "UPDATE_PLAYER";
export const DELETE_PLAYER = "DELETE_PLAYER";
export const SET_CURRENT_PLAYER = "SET_CURRENT_PLAYER";
export const CLEAR_CURRENT_PLAYER = "CLEAR_CURRENT_PLAYER";
export const SET_LOADING = "SET_LOADING";
export const PLAYERS_ERROR = "PLAYERS_ERROR";
